export const CHARACTERS = [
  {
    id: 'exec_male',
    label: 'Ejecutivo',
    icon: '👨‍💼',
    gender: 'M',
    desc: 'Traje sastre marino',
    skin: '#ffecd2',
    hair: '#1a1a1a',
    shirt: '#0f172a',
    shirt2: '#1e293b',
    pants: '#0f172a',
    shoes: '#0f0f0f',
    tie: '#1e40af',
  },
  {
    id: 'exec_female',
    label: 'Ejecutiva',
    icon: '👩‍💼',
    gender: 'F',
    desc: 'Blazer gris • coleta',
    skin: '#ffecd2',
    hair: '#7c2d12',
    shirt: '#334155',
    shirt2: '#475569',
    pants: '#1e293b',
    shoes: '#1a1a1a',
    tie: '#e11d48',
  },
  {
    id: 'worker_male',
    label: 'Obrero',
    icon: '👷',
    gender: 'M',
    desc: 'Casco y overol',
    skin: '#e8c4a8',
    hair: '#3a240c',
    shirt: '#ca8a04',
    shirt2: '#a16207',
    pants: '#1e3a8a',
    shoes: '#422006',
    tie: null,
  },
  {
    id: 'designer_female',
    label: 'Diseñadora',
    icon: '👩‍🎨',
    gender: 'F',
    desc: 'Streetwear colorido',
    skin: '#ffecd2',
    hair: '#f472b6',
    shirt: '#f9a8d4',
    shirt2: '#ec4899',
    pants: '#1f2937',
    shoes: '#f472b6',
    tie: null,
  },
  {
    id: 'police',
    label: 'Policía',
    icon: '👮',
    gender: 'M',
    desc: 'Uniforme azul',
    skin: '#ffecd2',
    hair: '#1e3a8a',
    shirt: '#1e40af',
    shirt2: '#1e3a8a',
    pants: '#1e293b',
    shoes: '#0f172a',
    tie: null,
  },
  {
    id: 'military_female',
    label: 'Militar',
    icon: '🪖',
    gender: 'F',
    desc: 'Camuflaje táctico',
    skin: '#e8c4a8',
    hair: '#365314',
    shirt: '#65a30d',
    shirt2: '#365314',
    pants: '#365314',
    shoes: '#1a2e05',
    tie: null,
  },
  {
    id: 'doctor_female',
    label: 'Médica',
    icon: '👩‍⚕️',
    gender: 'F',
    desc: 'Bata blanca',
    skin: '#ffecd2',
    hair: '#0f766e',
    shirt: '#ffffff',
    shirt2: '#e0f2fe',
    pants: '#e0f2fe',
    shoes: '#ffffff',
    tie: null,
  },
  {
    id: 'chef_male',
    label: 'Chef',
    icon: '👨‍🍳',
    gender: 'M',
    desc: 'Filipina y gorro',
    skin: '#ffecd2',
    hair: '#92400e',
    shirt: '#ffffff',
    shirt2: '#f8fafc',
    pants: '#1f2937',
    shoes: '#0f0f0f',
    tie: null,
  },
  {
    id: 'athlete_male',
    label: 'Deportista',
    icon: '🏃',
    gender: 'M',
    desc: 'Chándal deportivo',
    skin: '#e8c4a8',
    hair: '#1a1a1a',
    shirt: '#16a34a',
    shirt2: '#15803d',
    pants: '#14532d',
    shoes: '#16a34a',
    tie: null,
  },
  {
    id: 'student_female',
    label: 'Estudiante',
    icon: '👩‍🎓',
    gender: 'F',
    desc: 'Uniforme escolar',
    skin: '#ffecd2',
    hair: '#1e293b',
    shirt: '#a5b4fc',
    shirt2: '#3730a3',
    pants: '#1e293b',
    shoes: '#3730a3',
    tie: '#4f46e5',
  },
]

export const CHARACTER_IDS = CHARACTERS.map(c=>c.id)
export function getCharacter(id) { return CHARACTERS.find(c=>c.id===id) || CHARACTERS[0] }
